#!/bin/bash
# Obtain these keys from the Telstra Developer Portal
CONSUMER_KEY="DiL8SNygmWKsqGPNAPhG3POhXJGhG1GG"
CONSUMER_SECRET="0NGsHcHScxgwAGOa"
curl -X POST -H 'Content-Type: application/x-www-form-urlencoded' \
 -d "grant_type=client_credentials&client_id=$CONSUMER_KEY&client_secret=$CONSUMER_SECRET&scope=NSMS" \
 'https://tapi.telstra.com/v2/oauth/token'